version: '3.8'

services:
  flask:
    build: 
      context: ./app
      dockerfile: Dockerfile
    restart: always
    networks:
      - app_network
    environment:
      - FLASK_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask
    environment:
      - DOMAIN=${DOMAIN:-localhost}
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot_data:/etc/letsencrypt
      - certbot_webroot:/var/www/certbot
    networks:
      - app_network
    restart: always

volumes:
  certbot_data:
  certbot_webroot:

networks:
  app_network:
    driver: bridge