version: '3.8'

services:
  flask:
    build: .
    restart: always
    environment:
      - FLASK_ENV=production
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask
    networks:
      - app-network

networks:
  app-network:
    driver: bridge