FROM nginx:latest

# Install required packages
RUN apt-get update && \
    apt-get install -y \
    python3-certbot-nginx \
    certbot \
    netcat-traditional \
    openssl \
    cron && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Copy Nginx configuration
COPY nginx.conf /etc/nginx/nginx.conf

# Copy and setup SSL init script
COPY init-letsencrypt.sh /docker-entrypoint.d/
RUN chmod +x /docker-entrypoint.d/init-letsencrypt.sh